server:
  port: 10010
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 0
    jedis:
      pool:
        max-active: 1000
        max-wait: 2
        max-idle: 10
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000
      routes:
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/user/**
        - id: salary-service
          uri: lb://salaryservice
          predicates:
            - Path=/salary/**
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
        - id: invoice-service
          uri: lb://invoiceservice
          predicates:
            - Path=/dev-api/invoice/**
        - id: off-service
          uri: lb://offservice
          predicates:
            - Path=/off/**
